### ISSUE TITLE
Criar arquivo de regras para <SalesRights> para especificar regiões e países incluídos em <Territory>

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/scielobooks_exports#147]
É crescente o número de livros que possuem limites geográficos de distribuição devido a direitos de venda da editora. As regras podem ser desde a comercializar somente no Brasil, somente em países especificados ou não comercializar em alguns países.

Hoje a configuração padrão é:
```
<SalesRights>
        <SalesRightsType>01</SalesRightsType>
        <Territory>
                <RegionsIncluded>WORLD</RegionsIncluded>
        </Territory>
</SalesRights>
```

Preciso que seja criado um arquivo externo onde eu possa inserir os SBIDs dos livros que possuem alguma regra de `<SalesRights>`. Por exemplo:
3kq8w, `<CountriesIncluded>BR</CountriesIncluded>`
9nk5n, `<CountriesIncluded>BR</CountriesIncluded>`
mn2fn, `<CountriesExcluded>AO CV GW MZ ST GQ AL DE AD AT BE BY BA BG KZ CY HR DK SK SI ES EE FI FR GR HU IE IS IT LV LI LT LU MT MD MC ME NO ME PL PT CZ MK GB RO RU SM RS SE CH TR UA VA</CountriesExcluded>`

Livros vendidos somente no BR (exemplos de SBID: 3kq8w e 9nk5n)
```
<SalesRights>
        <SalesRightsType>01</SalesRightsType>
        <Territory>
                <CountriesIncluded>BR</CountriesIncluded>
        </Territory>
</SalesRights>
```

Livros que não devem ser vendidos em algum país (exemplo de SBID: mn2fn)
```
<SalesRights>
        <SalesRightsType>01</SalesRightsType>
        <Territory>
                <RegionsIncluded>WORLD</RegionsIncluded>
                <CountriesExcluded>AO CV GW MZ ST GQ AL DE AD AT BE BY BA BG KZ CY HR DK SK SI ES EE FI FR GR HU IE IS IT LV LI LT LU MT MD MC ME NO ME PL PT CZ MK GB RO RU SM RS SE CH TR UA VA</CountriesExcluded>
        </Territory>
</SalesRights>
```

**Comment by amandasramalho** [comment]
@ednilson arquivo de regras testado com os SBIDs que possuem regras e com SBIDs sem regras. Gerou corretamente em todos os casos.
SBIDs testados: 
3kq8w
9nk5n
mn2fn
7cs92
t267z
d823m
hz7bt
Editei o arquivo "sbid_data_entry.csv" direto no Excel e incluí mais regras de territórios, também gerou corretamente, o que me faz pensar que talvez não seja preciso ter o arquivo "sbid_data_entry.xlsx", pois é possível editar o próprio CSV.

**Comment by ednilson** [comment]
@amandasramalho ok vou remover o .xlsx
