### ISSUE TITLE
Incluir traços na data no nome do arquivo (_2018-03-16)

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/scielobooks_exports#64]
Edy, no nome do arquivo de saída possui uma data. Precisa que esta data esteja separada com traços.
Está assim: _20180316
Precisa ser assim: _2018-03-16

Esta definição está no tópico 5.3.1.2 deste documento: https://www.uksg.org/sites/uksg.org/files/KBART_Phase_I_Recommended_Practice.pdf

**Comment by ednilson** [comment]
@amandasramalho correção aplicada. Por favor verificar e fechar esse issue.

**Comment by amandasramalho** [comment]
Testado! Está tudo Ok. Obrigada!
