### ISSUE TITLE
Ajustar código de "ContributorRole" para outros perfis de autores

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/scielobooks_exports#83]
Dentro da tag de <Contributor>, precisamos ajustar o código da tag <ContributorRole> conforme regras:
`<ContributorRole>A01</ContributorRole> <!--Puxar do campo "creators/role".`
A01 para Individual Author, Corporate Author; 
B06 para Translator; 
B13 para Organizer;
B15 para Coordinator; 
B21 para Editor;
Z99 para Colaborator, Other. -->

Fonte: http://www.onix-codelists.io/codelist/17

**Comment by ednilson** [comment]
@amandasramalho você poderia me informar 1 SBID para cada caso acima. Isso vai agilizar o atendimento a esses issue.

**Comment by amandasramalho** [comment]
@ednilson pedi para que a Giovanna me enviasse. Segue: 
http://books.scielo.org/id/wy7ft - Autor individual
http://books.scielo.org/id/bwb4z - Corporate autor
http://books.scielo.org/id/fmnch - Translator
http://books.scielo.org/id/2yqzj - Organizer
http://books.scielo.org/id/6t3hs - Coordinator
http://books.scielo.org/id/74psp - Editor
http://books.scielo.org/id/zz66x - Organizer and Collaborator
http://books.scielo.org/id/t6bcg - Editor and organizer (no site só terá uma informação)
http://books.scielo.org/id/dydn3 -  Corporate autor anda Collaborator 
http://books.scielo.org/id/5h - Autor and collaborator

**Comment by ednilson** [comment]
@amandasramalho baixe o pacote, configure e teste.

**Comment by amandasramalho** [comment]
Testado! Está tudo Ok. Obrigada!
