### ISSUE TITLE
Conflito de codificação do publishers_ansi.json

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/scielobooks_exports#85]
Ao gerar o ONIX, acusa o erro:
INFO:__main__:[...]/2gm55
INFO:__main__:'utf-8' codec can't decode byte 0xe7 in position 43: invalid continuation byte

**Comment by ednilson** [comment]
O arquivo publishers.json deverá ser editado e salvo sempre em unicode UTF-8 e com quebra de linhas em CRLF (Windows)

`$ file publishers.json`
`publishers.json: UTF-8 Unicode text, with CRLF line terminators`

**Comment by ednilson** [comment]
@amandasramalho baixar o pacote e testar.

**Comment by amandasramalho** [comment]
ONIX gerado e tudo Ok!
