### ISSUE TITLE
Ajustes no texto da tag <EpubLicense>

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/scielobooks_exports#97]
@ednilson 
Precisamos alterar um texto na tag <EpubLicense> do ONIX.

Onde está:
epublicensename = Element('EpubLicenseName')
epublicensename.text = u'Creative Commons License'

Alterar para:
epublicensename.text = u'cc by'

**Comment by ednilson** [comment]
Aplicado por @amandasramalho diretamente no repositório.
