### ISSUE TITLE
Ajuste em <UnpricedItemType> para a Kobo

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/scielobooks_exports#98]
@ednilson 
A Kobo não está aceitando a tag <UnpricedItemType> para os títulos em acesso aberto.
É possível criar um script que somente considere preços como 0,00 em vez de inserir esta tag?
Em resumo, para a Kobo, é como desconsiderar a tag abaixo e deixar o ONIX incluir os preços com 0,00.
```
# UnpricedItemType
                if book['price_dollar'] == '0.00' and book['price_reais'] == '0.00':
                    unpriceditemtype = Element('UnpricedItemType')
                    unpriceditemtype.text = u'01'
                    supplydetail.append(unpriceditemtype)
```

**Comment by ednilson** [comment]
@amandasramalho decidimos comentar esse trecho de código e permitir que a tag PriceAmount apareça mesmo com valor == '0.00' comentando o trecho condicional.
